
# Spring configuration
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://${APP_DATASOURCE_URL}:${APP_DATASOURCE_PORT}/${APP_DATASOURCE_DATABASE}
      username: ${APP_DATASOURCE_USERNAME}
      password: ${APP_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
  devtools:
    add-properties: false
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    web: info

# General app configuration
app:
  mode: ${APP_MODE:DEVELOP}