
# Spring configuration
server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_URL}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  devtools:
    add-properties: false
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    web: info

# General app configuration
app:
  mode: ${MODE:DEVELOP}